/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ServerTest {
    @Test void test() {
        assertEquals(true, true);
    }
}
