/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

class ServerTest {
//
//	@Test
//	void testCommandMethods() {
//
//		HashMap<Command, Method> methods = new HashMap<>();
//
//		assertDoesNotThrow(new Executable() {
//			@Override
//			public void execute() throws Throwable {
//				for (Method m : Protocol.class.getMethods()) {
//					methods.put(Command.valueOf(m.getName().toUpperCase()), m);
//				}
//			}
//		});
//
//		assertEquals(methods.size(), Command.values().length, "missing implementation of command(s)");
//
//		for (Command cmd : methods.keySet()) {
//			Method m = methods.get(cmd);
//			assertEquals(m.getParameterCount(), cmd.getNumArgs(),
//					String.format("Method %s has %s arguments instead of %s as specified in Command.%s", m.getName(),
//							m.getParameterCount(), cmd.getNumArgs(), cmd));
//		}
//
//	}

}
