/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import java.io.IOException;
import java.net.ServerSocket;

import server.config.Config;
import server.db.DatabaseConnector;

public class Server {

	public final Config cfg;
	public final DatabaseConnector dbc;
	
	public static void main(String[] args) {

		new Server(Config.createFromArgs(args, Config.DEFAULT_CONFIG));

	}

	private Server(Config cfg) {

		this.cfg = cfg;
		dbc = new DatabaseConnector(cfg.DB_HOST, cfg.DB_PORT);

		System.out.println(String.format("Listening on port %s...", cfg.PORT));
		try (ServerSocket server = new ServerSocket(cfg.PORT)) {
			while (true) {
				ClientHandler.createThread(server.accept(), this);
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

}
